name = "logicalmechanism/fleamarket"
version = "1.0.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "A Hyperstructure Token Marketplace"

[repository]
user = "logicalmechanism"
project = "fleamarket"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
